# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Build and Publish
on:
  push:
concurrency:
  group: ${{ github.workflow }}
jobs:
  build:
    name: Build
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install build

      - id: semantic_version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: 'v'

      - name: Set version in pyproject.toml
        run: |
          version="${{ steps.semantic_version.outputs.version }}"
          sed -i "s/^version = .*/version = \"$version\"/" pyproject.toml

      - name: Build package
        run: python -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-test:
    name: Publish to Test PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    environment:
      name: testpypi
      url: https://test.pypi.org/p/trading212-api-py

    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          repository-url: https://test.pypi.org/legacy/

  release-text:
    name: Create Release Text
    needs:
      - build
      - publish-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Create release.txt
        run: |
          version="${{ github.ref_name }}"
          printf "Thank you for using trading212-api-py!\n\n" > release.txt
          printf "Documentation: https://github.com/clincha/trading212-api-py/tree/${version}/documentation" >> release.txt
          printf "Date: $(date -u +"%Y-%m-%d %H:%M:%S")" >> release.txt
          printf "PyPi: https://pypi.org/project/trading212-api-py/${version:1}" >> release.txt
          cat release.txt

      - name: Upload release.txt
        uses: actions/upload-artifact@v4
        with:
          name: release-text
          path: release.txt

  release:
    name: Create Release
    permissions:
      contents: write
    needs:
      - build
      - publish-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    environment:
      name: release

    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Download release.txt
        uses: actions/download-artifact@v4
        with:
          name: release-text
          path: release.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          body_path: release.txt
          files: dist/*

  publish:
    name: Publish to PyPI
    permissions:
      id-token: write
    needs:
      - build
      - publish-test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    environment:
      name: pypi
      url: https://pypi.org/p/trading212-api-py

    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
