# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Build and Publish
on:
  push:
    tags:
      - "v*"
concurrency:
  group: ${{ github.workflow }}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install build

      - id: semantic_version
        uses: paulhatch/semantic-version@v5.4.0

      - name: Set version in pyproject.toml
        run: |
          version="${{ steps.semantic_version.outputs.version }}"
          sed -i "s/^version = .*/version = \"$version\"/" pyproject.toml

      - name: Build package
        run: python -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  release:
    name: Create Release
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          body: |
            **Version**: `${{ steps.semantic_version.outputs.version }}`
            **Date**: `${{ github.event.release.published_at }}`
            **PyPi**: https://pypi.org/project/trading212-api-py/
          files: dist/*

  publish:
    name: Publish to PyPI
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/trading212-api-py

    permissions:
      id-token: write

    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
